public class Main {
    public static void main(String[] args) {

        temperaturometro temp = new temperaturometro();
        Persona p1 = new Persona();
        Persona p2 = new Persona();
        Persona p3 = new Persona();
        Persona p4 = new Persona();
        Persona p5 = new Persona();
        Persona p6 = new Persona();
        Persona p7 = new Persona();
        Persona p8 = new Persona();
        Persona p9 = new Persona();
        Persona p10 = new Persona();
        Persona p11 = new Persona();
        Persona p12 = new Persona();
        Persona p13 = new Persona();
        Persona p14 = new Persona();
        Persona p15 = new Persona();
        Persona p16 = new Persona();
        Persona p17 = new Persona();
        Persona p18 = new Persona();
        Persona p19 = new Persona();
        Persona p21 = new Persona();
        Persona p22 = new Persona();
        Persona p23 = new Persona();
        Persona p24 = new Persona();
        Persona p25 = new Persona();
        Persona p26 = new Persona();
        Persona p27 = new Persona();
        Persona p28 = new Persona();
        Persona p29 = new Persona();
        Persona p30 = new Persona();
        Persona p31 = new Persona();
        Persona p32 = new Persona();
        Persona p33 = new Persona();
        Persona p34 = new Persona();
        Persona p35 = new Persona();
        Persona p36 = new Persona();
        Persona p37 = new Persona();
        Persona p38 = new Persona();
        Persona p39 = new Persona();
        Persona p40 = new Persona();
        Persona p41 = new Persona();
        Persona p42 = new Persona();
        Persona p43 = new Persona();
        Persona p44 = new Persona();
        Persona p45 = new Persona();
        Persona p46 = new Persona();
        Persona p47 = new Persona();
        Persona p48 = new Persona();
        Persona p49 = new Persona();
        Persona p50 = new Persona();

        temp.start();

        p1.setPriority(8);
        p2.setPriority(8);
        p3.setPriority(8);
        p4.setPriority(8);
        p5.setPriority(8);
        p6.setPriority(8);

        p1.start();
        p2.start();
        p3.start();
        p4.start();
        p5.start();
        p6.start();
        p7.start();
        p8.start();
        p9.start();
        p10.start();
        p11.start();
        p12.start();
        p13.start();
        p14.start();
        p15.start();
        p16.start();
        p17.start();
        p18.start();
        p19.start();
        p21.start();
        p22.start();
        p23.start();
        p24.start();
        p25.start();
        p26.start();
        p27.start();
        p28.start();
        p29.start();
        p30.start();
        p31.start();
        p32.start();
        p33.start();
        p34.start();
        p35.start();
        p36.start();
        p37.start();
        p38.start();
        p39.start();
        p40.start();
        p41.start();
        p42.start();
        p43.start();
        p44.start();
        p45.start();
        p46.start();
        p47.start();
        p48.start();
        p49.start();
        p50.start();

    }
}